apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/django/.dbdata"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-django-deployment
  labels:
    app: db-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-django
  template:
    metadata:
      labels:
        app: db-django
    spec:
      containers:
        - name: db-django
          image: mysql:8
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "4Gi"
              cpu: "0.5"
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-django-secret
                  key: database  

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-django-secret
                  key: user  

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-django-secret
                  key: pass  

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-django-secret
                  key: root_pass   
                  
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-django-service
spec:
  selector:
    app: db-django
  ports:
    - port: 3306
  clusterIP: None