apiVersion: apps/v1
kind: Deployment
metadata:
  name: dj-app-deployment
  labels:
    app: dj-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dj-app
  template:
    metadata:
      labels:
        app: dj-app
    spec:
      containers:
        - name: dj-app
          image: senjespakk/django-app
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "250Mi"
              cpu: "0.3"
            limits:
              memory: "500Mi"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: dj-app-service
spec:  
  selector:
    app: dj-app
  ports:
    - protocol: TCP
      port: 8000