apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/admin/.dbdata"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dj-db-deployment
  labels:
    app: dj-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dj-db
  template:
    metadata:
      labels:
        app: dj-db
    spec:
      containers:
        - name: dj-db
          image: mysql:5.7.22
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "2Gi"
              cpu: "0.3"
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dj-db-secret
                  key: database  

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: dj-db-secret
                  key: user  

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dj-db-secret
                  key: pass  

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dj-db-secret
                  key: root_pass   
                  
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: dj-db-service
spec:
  selector:
    app: dj-db
  ports:
    - port: 3306
  clusterIP: None