apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  labels:
    app: reactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: reactapp
          image: senjespakk/react-app
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.3"
            limits:
              memory: "515Mi"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
spec:
  type: LoadBalancer
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 3000
