apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata: 
  name: letsencrypt-prod
spec: 
  acme: 
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "imperotechne16@hotmail.com"
    solvers:
      - http01:
        ingress:
          class: nginx
        selector: {}    
    privateKeySecretRef: 
      name: letsencrypt-prod
